# Generated by Django 6.1.1 on 2026-09-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepart',
            name='negotiable',
            field=models.BooleanField(default=False, help_text='Tick if price can be negotiated at sale time'),
        ),
    ]
