# Generated by Django 6.1.1 on 2026-09-22 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('motorcycles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictiveAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_part', models.CharField(max_length=150)),
                ('reason', models.TextField()),
                ('due_mileage', models.PositiveIntegerField()),
                ('is_done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('motorcycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='motorcycles.motorcycle')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField(auto_now_add=True)),
                ('mileage', models.PositiveIntegerField(help_text='Odometer at service time')),
                ('description', models.TextField()),
                ('parts_replaced', models.TextField(blank=True)),
                ('next_due_mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('motorcycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='motorcycles.motorcycle')),
            ],
        ),
    ]
