# Generated by Django 6.1.1 on 2026-09-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_sparepart_negotiable'),
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('labour_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('negotiable', models.BooleanField(default=False)),
                ('parts', models.ManyToManyField(blank=True, related_name='services', to='inventory.sparepart')),
            ],
        ),
    ]
