# Generated by Django 6.1.1 on 2026-09-22 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_labour_charge_sale_service_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS')], default='whatsapp', max_length=10)),
                ('body', models.TextField()),
                ('status', models.CharField(default='logged', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_messages', to='sales.sale')),
            ],
        ),
    ]
