# Generated by Django 6.1.1 on 2026-09-22 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('inventory', '0002_sparepart_negotiable'),
        ('motorcycles', '0001_initial'),
        ('sales', '0003_billmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='billmessage',
            name='kind',
            field=models.CharField(choices=[('estimate', 'Pre-service estimate'), ('final_bill', 'Final bill'), ('completion_alert', 'Service completion alert')], default='final_bill', max_length=20),
        ),
        migrations.AlterField(
            model_name='billmessage',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill_messages', to='sales.sale'),
        ),
        migrations.AlterField(
            model_name='billmessage',
            name='status',
            field=models.CharField(default='logged', max_length=60),
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_note', models.CharField(blank=True, max_length=200)),
                ('labour_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent to customer'), ('approved', 'Approved'), ('completed', 'Service done')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to='customers.customer')),
                ('motorcycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimates', to='motorcycles.motorcycle')),
                ('sale', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimate', to='sales.sale')),
            ],
        ),
        migrations.AddField(
            model_name='billmessage',
            name='estimate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='sales.estimate'),
        ),
        migrations.CreateModel(
            name='EstimateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.estimate')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.sparepart')),
            ],
        ),
    ]
